fisp release -Dopumd static,template,config,plugin --no-color -r common
fisp release -Dopumd static,template,config --no-color -r transit
fisp release -Dopumd static,template,config --no-color -r place
fisp release -Dopumd static,template,config --no-color -r index
fisp release -Dopumd static,template,config --no-color -r addr
fisp release -Dopumd static,template,config --no-color -r feedback
fisp release -Dopumd static,template,config --no-color -r drive
fisp release -Dopumd static,template,config --no-color -r walk
fisp release -Dopumd static,template,config --no-color -r third
fisp release -Dopumd static,template,config --no-color -r user
fisp release -Dopumd static,template,config --no-color -r taxi